// <auto-generated />
using System;
using ApiCashback.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCashback.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220801135233_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiCashback.Models.CashbackPercentual", b =>
                {
                    b.Property<int>("CashbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CashbackId"), 1L, 1);

                    b.Property<double>("Domingo")
                        .HasColumnType("float");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quarta")
                        .HasColumnType("float");

                    b.Property<double>("Quinta")
                        .HasColumnType("float");

                    b.Property<double>("Sabado")
                        .HasColumnType("float");

                    b.Property<double>("Segunda")
                        .HasColumnType("float");

                    b.Property<double>("Sexta")
                        .HasColumnType("float");

                    b.Property<double>("Terca")
                        .HasColumnType("float");

                    b.HasKey("CashbackId");

                    b.ToTable("CashbackPercentuais");

                    b.HasData(
                        new
                        {
                            CashbackId = 1,
                            Domingo = 0.25,
                            Marca = "Sokl",
                            Quarta = 0.02,
                            Quinta = 0.10000000000000001,
                            Sabado = 0.20000000000000001,
                            Segunda = 0.070000000000000007,
                            Sexta = 0.14999999999999999,
                            Terca = 0.059999999999999998
                        },
                        new
                        {
                            CashbackId = 2,
                            Domingo = 0.29999999999999999,
                            Marca = "Brahma",
                            Quarta = 0.14999999999999999,
                            Quinta = 0.20000000000000001,
                            Sabado = 0.29999999999999999,
                            Segunda = 0.050000000000000003,
                            Sexta = 0.25,
                            Terca = 0.10000000000000001
                        },
                        new
                        {
                            CashbackId = 3,
                            Domingo = 0.34999999999999998,
                            Marca = "Stella",
                            Quarta = 0.80000000000000004,
                            Quinta = 0.13,
                            Sabado = 0.25,
                            Segunda = 0.029999999999999999,
                            Sexta = 0.17999999999999999,
                            Terca = 0.5
                        },
                        new
                        {
                            CashbackId = 4,
                            Domingo = 0.40000000000000002,
                            Marca = "Bohemia",
                            Quarta = 0.14999999999999999,
                            Quinta = 0.14999999999999999,
                            Sabado = 0.40000000000000002,
                            Segunda = 0.10000000000000001,
                            Sexta = 0.20000000000000001,
                            Terca = 0.14999999999999999
                        });
                });

            modelBuilder.Entity("ApiCashback.Models.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<double>("ValorCashBack")
                        .HasColumnType("float");

                    b.Property<int>("VendaID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaID");

                    b.ToTable("ItensVendas");
                });

            modelBuilder.Entity("ApiCashback.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"), 1L, 1);

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecoVenda")
                        .HasColumnType("float");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProdutoId");

                    b.ToTable("CatalogoCervejas");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            Marca = "Skol",
                            PrecoVenda = 4.5800000000000001,
                            Tipo = "Cerveja"
                        },
                        new
                        {
                            ProdutoId = 2,
                            Marca = "Brahma",
                            PrecoVenda = 5.3399999999999999,
                            Tipo = "Cerveja"
                        },
                        new
                        {
                            ProdutoId = 3,
                            Marca = "Stella",
                            PrecoVenda = 6.79,
                            Tipo = "Cerveja"
                        },
                        new
                        {
                            ProdutoId = 4,
                            Marca = "Skol",
                            PrecoVenda = 6.8399999999999999,
                            Tipo = "Cerveja"
                        });
                });

            modelBuilder.Entity("ApiCashback.Models.Venda", b =>
                {
                    b.Property<int>("VendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendaId"), 1L, 1);

                    b.Property<double>("CashBackTotalVenda")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime2");

                    b.Property<double>("ValorTotalItens")
                        .HasColumnType("float");

                    b.HasKey("VendaId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("ApiCashback.Models.ItemVenda", b =>
                {
                    b.HasOne("ApiCashback.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.HasOne("ApiCashback.Models.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ApiCashback.Models.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
