// <auto-generated />
using System;
using ApiCashback.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCashback.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220801122616_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiCashback.Models.CashbackPercentual", b =>
                {
                    b.Property<int>("CashbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CashbackId"), 1L, 1);

                    b.Property<decimal>("Domingo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quarta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quinta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sabado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Segunda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sexta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Terca")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CashbackId");

                    b.ToTable("CashbackPercentuais");
                });

            modelBuilder.Entity("ApiCashback.Models.Cerveja", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"), 1L, 1);

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProdutoId");

                    b.ToTable("CatalogoCervejas");
                });

            modelBuilder.Entity("ApiCashback.Models.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCashBack")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendaID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaID");

                    b.ToTable("ItensVendas");
                });

            modelBuilder.Entity("ApiCashback.Models.Venda", b =>
                {
                    b.Property<int>("VendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendaId"), 1L, 1);

                    b.Property<decimal>("CashBackTotalVenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorTotalItens")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VendaId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("ApiCashback.Models.ItemVenda", b =>
                {
                    b.HasOne("ApiCashback.Models.Cerveja", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.HasOne("ApiCashback.Models.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ApiCashback.Models.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
